name: Quality Gates

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-gates:
    runs-on: ubuntu-latest
    
    env:
      CI: true
      NODE_ENV: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: delayguard-app/package-lock.json
        
    - name: Install dependencies
      working-directory: ./delayguard-app
      run: npm ci
      
    - name: Copy test environment
      working-directory: ./delayguard-app
      run: cp .env.test .env
      
    - name: Run Quality Gates
      working-directory: ./delayguard-app
      run: node scripts/quality-gates.js
      env:
        NODE_ENV: test
      
    - name: Upload coverage reports
      if: always()
      uses: codecov/codecov-action@v3
      with:
        file: ./delayguard-app/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
